Test bachir
hommingcom/programming-proficiency-test pull request #34
Opened 2023-05-16 08:57 UTC by Bachir93

Change

2023-05-16 08:58 UTC, Bachir93 commented
Change

2023-05-16 09:52 UTC, ruvaler requested changes

2023-05-16 09:52 UTC, ruvaler commented on resources/App.vue
> +import PropertyList from './TestBachir/components/PropertyList.vue';
Cuidado con las rutas, no pongas tu nombre en carpetas dentro del proyecto, además puedes usar el alias @ para que te sea más sencillo.

2023-05-16 09:52 UTC, ruvaler commented on resources/TestBachir/components/PropertyList.vue
> +        .filter((obj) => obj !== null); // Delete the objects null
El filter sobra ya que no te van a venir properties a null. De todas formas, en caso de ser necesario, es mejor meter este filter delante del map, ya que así es mucho más eficiente, primero quitar los elementos que no vayas a querer y después de eso ya los muestras a tu gusto.

2023-05-16 09:52 UTC, ruvaler commented on resources/mocks/api.js
> +
Cuidado con los espacios en blanco innecesarios

2023-05-16 09:52 UTC, ruvaler commented on resources/TestBachir/components/PropertyList.vue
> +    <button class="btn btn-primary m-2" @click="filterUsers">Filter by users</button>
qué son estos botones para filtrar por usuario? cómo filtrarás por usuario si le clicas al botón?

Piensa qué componente debería ir aquí para poder filtrar los inmuebles dependiendo del usuario que esté asignado a ellos. Igual con los selectores de tipo que tienes abajo de este

2023-05-16 09:52 UTC, ruvaler commented on resources/TestBachir/components/PropertyList.vue
> +          <td>{{ combinedObject.id }}</td>
Creo que en esta tabla tienes columnas que son innecesarias, qué valor aporta a un usuario ver el ID del usuario que tiene un inmueble? Deja solo aquellos que aporten información relevante.

2023-05-16 09:52 UTC, ruvaler commented on resources/TestBachir/components/PropertyList.vue
> +      this.properties = this.copyProperties;
Para qué necesitas este copy properties? En lugar de hacerlo así, puedes asignar el valor directamente del objeto javascript donde está moqueada la API, es decir, en este caso propertiesData

2023-05-16 09:52 UTC, ruvaler commented on resources/TestBachir/components/PropertyList.vue
> +      this.propertyTypes = this.copyPropertyTypes;
Lo mismo que te dije en copy properties

2023-05-16 09:52 UTC, ruvaler commented on resources/TestBachir/components/PropertyList.vue
> +      this.users = this.copyUsers;
Lo mismo que te dije en copy properties

2023-05-16 09:52 UTC, ruvaler commented on resources/TestBachir/components/PropertyList.vue
> +    rentalDuration(property) {
En lugar de hacerlo así, será mejor coger las dos fechas  y hacer esto:
O sea: ((año to * 12) + mes to) - ((año from * 12) + mes from) 

Creo que es mas eficiente además de enterderse mejor qué se quiere hacer

2023-05-16 09:52 UTC, ruvaler commented on resources/TestBachir/components/PropertyList.vue
> +    forRent(property) {
Cuidado porque no siempre un inmueble tiene rentedFrom y rentedTo. Comprueba eso antes de devolver un valor

2023-05-16 09:52 UTC, ruvaler commented on resources/TestBachir/components/PropertyList.vue
> +            userId1: this.users[index].id,
Esto qué es? por que hacer _this.users[index]_? Lo que tienes que hacer es buscar dentro del listado de usuarios cual es el que tiene un ID igual al userId del inmueble. Y no tienes que modificar los datos de la API para que te concuerden con lo que has hecho. Mírate el método **find** para arrays de javascript

2023-05-16 09:52 UTC, ruvaler commented on resources/TestBachir/components/PropertyList.vue
> +            typeId1: this.propertyTypes[index].id,
Igual que con los users que te dije arriba

2023-05-16 09:52 UTC, ruvaler commented on resources/mocks/api.js
> +  {
No sé por qué has modificado los datos mock de la API. Has hecho una adecuación para que te funcionase la app y eso no se debe hacer nunca, tú tienes que amoldarte a la API, no ella a ti

2023-05-16 10:34 UTC, Bachir93 commented on resources/App.vue
> +import PropertyList from './TestBachir/components/PropertyList.vue';
Corregido

2023-05-16 10:52 UTC, Bachir93 commented on resources/TestBachir/components/PropertyList.vue
> +        .filter((obj) => obj !== null); // Delete the objects null
Fue un parche en su momento. Lo quito

2023-05-16 10:57 UTC, Bachir93 commented on resources/mocks/api.js
> +
Hecho

2023-05-16 11:55 UTC, Bachir93 commented on resources/TestBachir/components/PropertyList.vue
> +    <button class="btn btn-primary m-2" @click="filterUsers">Filter by users</button>
La condición es interna... Dependiendo del valor obtenido en el input, puedo filtrar por users, propertyTypes o properties, cada botón corresponde a un objeto. Hecho de una forma simple... Cada vez que clicamos sobre un determinado botón, llamamos a la función asignada para dicho botón....

2023-05-17 10:19 UTC, ruvaler commented on resources/TestBachir/components/PropertyList.vue
> +    <button class="btn btn-primary m-2" @click="filterUsers">Filter by users</button>
Eso no está bien, no es intuitivo, además deberías poder filtrar por varios campos a la vez. La forma correcta de hacer esto es con un selector para cada uno, y que se pueda filtrar por uno, varios o ninguno. Es decir, haciendo un filter en una propiedad computada, que será la que se le pase a la tabla

2023-11-02 08:29 UTC, closed without merging